board: 6 Pack
name: Davids MPCNC

stepping:
    engine: I2S_STREAM
    idle_ms: 250
    pulse_us: 4
    dir_delay_us: 1
    disable_delay_us: 0

axes:
    shared_stepper_disable_pin: NO_PIN
    x:
        steps_per_mm: 248.000
        max_rate_mm_per_min: 8000.000
        acceleration_mm_per_sec2: 300.000
        max_travel_mm: 800.000
        soft_limits: true
        homing:
          cycle: 2
          positive_direction: false
          mpos_mm: 0.000
          feed_mm_per_min: 200.000
          seek_mm_per_min: 1000.000
          settle_ms: 100
          seek_scaler: 1.100
          feed_scaler: 1.100

        motor0:
            limit_neg_pin: gpio.32
            limit_pos_pin: NO_PIN
            limit_all_pin: NO_PIN
            hard_limits: false
            pulloff_mm: 10.000
            tmc_2130:

                # Motor Socket #1 (Left End)
                # Note that the order varies between motor slots!
                # See https://github.com/bdring/6-Pack_CNC_Controller/wiki/Setting-Up-Axis-Motors#assigning-io-pins-to-motors
                disable_pin:   i2so.0
                direction_pin: i2so.1
                step_pin:      i2so.2
                cs_pin:        i2so.3

                r_sense_ohms: 0.110
                run_amps:     0.750
                hold_amps:    0.750

                microsteps: 64

                stallguard: 0
                stallguard_debug: false
                toff_disable: 0
                toff_stealthchop: 5
                toff_coolstep: 3
                run_mode: StealthChop
                homing_mode: StealthChop
                use_enable: false

        motor1:
            limit_neg_pin: gpio.33
            limit_pos_pin: NO_PIN
            limit_all_pin: NO_PIN
            hard_limits: false
            pulloff_mm: 10.000
            tmc_2130:

                # Motor Socket #2
                # Note that the order varies between motor slots!
                # See https://github.com/bdring/6-Pack_CNC_Controller/wiki/Setting-Up-Axis-Motors#assigning-io-pins-to-motors
                disable_pin:   i2so.7
                direction_pin: i2so.4:low
                step_pin:      i2so.5
                cs_pin:        i2so.6

                r_sense_ohms: 0.110
                run_amps:     0.750
                hold_amps:    0.750

                microsteps: 64

                stallguard: 0
                stallguard_debug: false
                toff_disable: 0
                toff_stealthchop: 5
                toff_coolstep: 3
                run_mode: StealthChop
                homing_mode: StealthChop
                use_enable: false

    y:
        steps_per_mm: 248.000
        max_rate_mm_per_min: 8000.000
        acceleration_mm_per_sec2: 300.000
        max_travel_mm: 300.000
        soft_limits: false
        homing:
          cycle: 3
          positive_direction: false
          mpos_mm: 0.000
          feed_mm_per_min: 200.000
          seek_mm_per_min: 1000.000
          settle_ms: 500
          seek_scaler: 1.100
          feed_scaler: 1.100

        motor0:
            limit_neg_pin: gpio.34
            limit_pos_pin: NO_PIN
            limit_all_pin: NO_PIN
            hard_limits: false
            pulloff_mm: 10.000
            tmc_2130:

                # Motor Socket #3
                # Note that the order varies between motor slots!
                # See https://github.com/bdring/6-Pack_CNC_Controller/wiki/Setting-Up-Axis-Motors#assigning-io-pins-to-motors
                disable_pin:   i2so.8
                direction_pin: i2so.9:low
                step_pin:      i2so.10
                cs_pin:        i2so.11

                r_sense_ohms: 0.110
                run_amps:     0.750
                hold_amps:    0.750

                microsteps: 64

                stallguard: 0
                stallguard_debug: false
                toff_disable: 0
                toff_stealthchop: 5
                toff_coolstep: 3
                run_mode: StealthChop
                homing_mode: StealthChop
                use_enable: false

        motor1:
            limit_neg_pin: gpio.35
            limit_pos_pin: NO_PIN
            limit_all_pin: NO_PIN
            hard_limits: false
            pulloff_mm: 10.000
            tmc_2130:

                # Motor Socket #4
                # Note that the order varies between motor slots!
                # See https://github.com/bdring/6-Pack_CNC_Controller/wiki/Setting-Up-Axis-Motors#assigning-io-pins-to-motors
                disable_pin:   i2so.15
                direction_pin: i2so.12
                step_pin:      i2so.13
                cs_pin:        i2so.14

                r_sense_ohms: 0.110
                run_amps:     0.750
                hold_amps:    0.750

                microsteps: 64

                stallguard: 0
                stallguard_debug: false
                toff_disable: 0
                toff_stealthchop: 5
                toff_coolstep: 3
                run_mode: StealthChop
                homing_mode: StealthChop
                use_enable: false

    z:
        steps_per_mm: 575.000
        max_rate_mm_per_min: 3000.000
        acceleration_mm_per_sec2: 200.000
        max_travel_mm: 130.000
        soft_limits: false
        # homing:
        #   cycle: 1
        #   positive_direction: false
        #   mpos_mm: 150.000
        #   feed_mm_per_min: 100.000
        #   seek_mm_per_min: 200.000
        #   settle_ms: 500
        #   seek_scaler: 1.100
        #   feed_scaler: 1.100

        motor0:
            limit_neg_pin: NO_PIN
            limit_pos_pin: NO_PIN
            limit_all_pin: NO_PIN
            hard_limits: false
            pulloff_mm: 10.000
            tmc_2130:

                # Motor Socket #5
                # Note that the order varies between motor slots!
                # See https://github.com/bdring/6-Pack_CNC_Controller/wiki/Setting-Up-Axis-Motors#assigning-io-pins-to-motors
                disable_pin:   i2so.16
                direction_pin: i2so.17:low
                step_pin:      i2so.18
                cs_pin:        i2so.19

                r_sense_ohms: 0.110
                run_amps:     0.750
                hold_amps:    0.750

                microsteps: 64

                stallguard: 0
                stallguard_debug: false
                toff_disable: 0
                toff_stealthchop: 5
                toff_coolstep: 3
                run_mode: StealthChop
                homing_mode: StealthChop
                use_enable: false

i2so:
    bck_pin:  gpio.22
    data_pin: gpio.21
    ws_pin:   gpio.17

spi:
    miso_pin: gpio.19
    mosi_pin: gpio.23
    sck_pin:  gpio.18

sdcard:
    cs_pin: gpio.5
    card_detect_pin: NO_PIN

# control:
#     safety_door_pin: NO_PIN
#     reset_pin:       NO_PIN
#     feed_hold_pin:   NO_PIN
#     cycle_start_pin: NO_PIN
#     macro0_pin:      NO_PIN
#     macro1_pin:      NO_PIN
#     macro2_pin:      NO_PIN
#     macro3_pin:      NO_PIN
#
# coolant:
#     flood_pin: NO_PIN
#     mist_pin:  NO_PIN
#     delay_ms:  0
#
# probe:
#     pin: NO_PIN
#     check_mode_start: true

macros:
    startup_line0:
    startup_line1:
    macro0:
    macro1:
    macro2:
    macro3:

start:
    must_home: false

PWM:
    pwm_hz:          5000
    output_pin:      gpio.14
    enable_pin:      gpio.13
    direction_pin:   NO_PIN
    disable_with_s0: false
    s0_with_disable: true
    spinup_ms:       1000
    spindown_ms:     1000
    tool_num:        0
    speed_map:       0=0.000% 1000=100.000%
